I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 10, in script
    scene black with circleirisin
  File "game/script.rpy", line 10, in <module>
    scene black with circleirisin
NameError: name 'circleirisin' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 10, in script
    scene black with circleirisin
  File "D:\HyHOE\renpy\renpy-6.99.12.4-sdk\renpy\ast.py", line 1353, in execute
    paired = renpy.python.py_eval(self.paired)
  File "D:\HyHOE\renpy\renpy-6.99.12.4-sdk\renpy\python.py", line 1944, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\HyHOE\renpy\renpy-6.99.12.4-sdk\renpy\python.py", line 1937, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 10, in <module>
    scene black with circleirisin
NameError: name 'circleirisin' is not defined

Windows-7-6.1.7601-SP1
Ren'Py 7.1.0.882
claustrum 1.0
Wed Nov 21 15:40:51 2018
